// AUTO-GENERATED by pricing-engine on 2026-06-21T04:05:46.632Z.
// Source(s): live /api/pricing (Google Sheet). DO NOT EDIT BY HAND,
// edit pricing-engine/config.js and re-run `node build-prices.js`.
// Drop-in replacement for /pricing-data.js (same window.PRICING shape).
window.PRICING = {
  "iphone": {
    "headers": [
      "Model",
      "Unlocked / Apple",
      "Carrier / Locked"
    ],
    "rows": [
      [
        "iPhone 17 Pro Max 2tb",
        "$1,241",
        "$788"
      ],
      [
        "iPhone 17 Pro Max 1tb",
        "$1,050",
        "$750"
      ],
      [
        "iPhone 17 Pro Max 512gb",
        "$975",
        "$683"
      ],
      [
        "iPhone 17 Pro Max 256gb",
        "$855",
        "$623"
      ],
      [
        "iPhone 17 Pro 1tb",
        "$875",
        "$638"
      ],
      [
        "iPhone 17 Pro 512gb",
        "$725",
        "$578"
      ],
      [
        "iPhone 17 Pro 256gb",
        "$665",
        "$525"
      ],
      [
        "iPhone 17 Air 1tb",
        "$713",
        "$428"
      ],
      [
        "iPhone 17 Air 512gb",
        "$619",
        "$390"
      ],
      [
        "iPhone 17 Air 256gb",
        "$544",
        "$338"
      ],
      [
        "iPhone 17 512gb",
        "$630",
        "$420"
      ],
      [
        "iPhone 17 256gb",
        "$525",
        "$375"
      ],
      [
        "iPhone 16 Pro Max 1tb",
        "$825",
        "$600"
      ],
      [
        "iPhone 16 Pro Max 512gb",
        "$750",
        "$525"
      ],
      [
        "iPhone 16 Pro Max 256gb",
        "$600",
        "$450"
      ],
      [
        "iPhone 16 Pro 1tb",
        "$735",
        "$518"
      ],
      [
        "iPhone 16 Pro 512gb",
        "$660",
        "$480"
      ],
      [
        "iPhone 16 Pro 256gb",
        "$585",
        "$405"
      ],
      [
        "iPhone 16 Pro 128gb",
        "$510",
        "$330"
      ],
      [
        "iPhone 16 Plus 512gb",
        "$480",
        "$368"
      ],
      [
        "iPhone 16 Plus 256gb",
        "$443",
        "$330"
      ],
      [
        "iPhone 16 Plus 128gb",
        "$405",
        "$255"
      ],
      [
        "iPhone 15 Pro Max 256gb",
        "$450",
        "$330"
      ],
      [
        "iPhone 15 Pro Max 512gb",
        "$488",
        "$368"
      ],
      [
        "iPhone 15 Pro Max 1tb",
        "$525",
        "$405"
      ],
      [
        "iPhone 15 Pro 128gb",
        "$413",
        "$263"
      ],
      [
        "iPhone 15 Pro 256gb",
        "$450",
        "$300"
      ],
      [
        "iPhone 15 Pro 512gb",
        "$488",
        "$338"
      ],
      [
        "iPhone 15 Pro 1tb",
        "$525",
        "$375"
      ],
      [
        "iPhone 15 Plus 128gb",
        "$263",
        "$188"
      ],
      [
        "iPhone 15 Plus 256gb",
        "$300",
        "$225"
      ],
      [
        "iPhone 15 Plus 512gb",
        "$338",
        "$263"
      ],
      [
        "iPhone 14 Pro Max 128gb",
        "$375",
        "$263"
      ],
      [
        "iPhone 14 Pro Max 256gb",
        "$413",
        "$300"
      ],
      [
        "iPhone 14 Pro Max 512gb",
        "$450",
        "$338"
      ],
      [
        "iPhone 14 Pro Max 1tb",
        "$488",
        "$375"
      ],
      [
        "iPhone 14 Pro 128gb",
        "$338",
        "$225"
      ],
      [
        "iPhone 14 Pro 256gb",
        "$375",
        "$263"
      ],
      [
        "iPhone 14 Pro 512gb",
        "$413",
        "$300"
      ],
      [
        "iPhone 14 Pro 1tb",
        "$450",
        "$338"
      ],
      [
        "iPhone 14 Plus 128gb",
        "$188",
        "$98"
      ],
      [
        "iPhone 14 Plus 256gb",
        "$225",
        "$128"
      ],
      [
        "iPhone 14 Plus 512gb",
        "$263",
        "$150"
      ],
      [
        "iPhone 13 Pro Max 128gb",
        "$300",
        "$225"
      ],
      [
        "iPhone 13 Pro Max 256gb",
        "$338",
        "$263"
      ],
      [
        "iPhone 13 Pro Max 512gb",
        "$375",
        "$300"
      ],
      [
        "iPhone 13 Pro Max 1tb",
        "$413",
        "$338"
      ],
      [
        "iPhone 13 Pro 128gb",
        "$300",
        "$188"
      ],
      [
        "iPhone 13 Pro 256gb",
        "$338",
        "$225"
      ],
      [
        "iPhone 13 Pro 512gb",
        "$375",
        "$263"
      ],
      [
        "iPhone 13 Pro 1tb",
        "$413",
        "$300"
      ],
      [
        "iPhone 13 Mini 128gb",
        "$75",
        "$60"
      ],
      [
        "iPhone 13 Mini 256gb",
        "$113",
        "$75"
      ],
      [
        "iPhone 13 Mini 512gb",
        "$150",
        "$94"
      ]
    ]
  },
  "macbook-pro": {
    "headers": [
      "Model",
      "Discount on MSRP",
      "Activation bonus"
    ],
    "rows": [
      [
        "14in M5 24GB 1TB SSD 2025",
        "50% off MSRP",
        "ACTIVE = -$100"
      ],
      [
        "14in M5 16GB 1TB SSD 2025",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M5 16GB 512GB SSD 2025",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M4 MAX 48GB 1TB SSD",
        "50% off MSRP",
        "ACTIVE = -$100"
      ],
      [
        "16in M4 MAX 36GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M4 PRO 48GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M4 PRO 24GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M4 MAX 36GB 1TB SSD",
        "50% off MSRP",
        "ACTIVE = -$100"
      ],
      [
        "14in M4 PRO 24GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M4 PRO 24GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M4 24GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M4 16GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M4 16GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M3 MAX 48GB 1TB SSD",
        "50% off MSRP",
        "ACTIVE = -$100"
      ],
      [
        "16in M3 MAX 36GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M3 PRO 36GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "16in M3 PRO 18GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M3 MAX 36GB 1TB SSD",
        "50% off MSRP",
        "ACTIVE = -$100"
      ],
      [
        "14in M3 PRO 18GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M3 PRO 18GB 512GB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M3 8GB 1TB SSD",
        "50% off MSRP",
        "-"
      ],
      [
        "14in M3 8GB 512GB SSD",
        "50% off MSRP",
        "-"
      ]
    ]
  },
  "macbook-air": {
    "headers": [
      "Model",
      "Price",
      "Activation bonus"
    ],
    "rows": [
      [
        "15\" 24GB 512GB SSD M4",
        "$976",
        "ACTIVE = -$100"
      ],
      [
        "15\" 16GB 512GB SSD M4",
        "$816",
        "-"
      ],
      [
        "15\" 16GB 256GB SSD M4",
        "$680",
        "-"
      ],
      [
        "13\" 24GB 512GB SSD M4",
        "$840",
        "ACTIVE = -$100"
      ],
      [
        "13\"16GB 512GB SSD M4",
        "$680",
        "-"
      ],
      [
        "13\" 16GB 256GB SSD M4",
        "$560",
        "-"
      ],
      [
        "15in M3 24GB 512GB SSD",
        "$760",
        "ACTIVE = -$50"
      ],
      [
        "15in M3 16GB 256GB SSD",
        "$600",
        "-"
      ],
      [
        "13in M3 24GB 512GB SSD",
        "$680",
        "-"
      ],
      [
        "13in M3 16GB 256GB SSD",
        "$480",
        "-"
      ],
      [
        "13in M2 16GB 256GB SSD",
        "$400",
        "-"
      ],
      [
        "15in M3 16GB 512GB SSD",
        "$720",
        "ACTIVE = -$50"
      ],
      [
        "15in M3 8GB 512GB SSD",
        "$640",
        "-"
      ],
      [
        "15in M3 8GB 256GB SSD",
        "$520",
        "-"
      ],
      [
        "13in M3 16GB 512GB SSD",
        "$520",
        "ACTIVE = -$50"
      ],
      [
        "13in M3 8GB 512GB SSD",
        "$440",
        "-"
      ],
      [
        "13in M3 8GB 256GB SSD",
        "$400",
        "-"
      ],
      [
        "15in M2 8GB 512GB SSD",
        "$520",
        "-"
      ],
      [
        "15in M2 8GB 256GB SSD",
        "$400",
        "ACTIVE = -$50"
      ]
    ]
  },
  "mac-mini": {
    "headers": [
      "Model",
      "Price",
      "Note"
    ],
    "rows": [
      [
        "MCX44LL/A PRO 24GB Memory 512GB",
        "$675",
        "-"
      ],
      [
        "MCYT4LL/A 24GB Memory - 512GB",
        "$450",
        "-"
      ],
      [
        "MU9E3LL/A 16GB Memory - 512GB",
        "$375",
        "-"
      ],
      [
        "MU9D3LL/A 16GB Memory - 256GB",
        "$300",
        "-"
      ]
    ]
  },
  "apple-watch": {
    "headers": [
      "Model",
      "Price",
      "Note"
    ],
    "rows": [
      [
        "ULTRA 3 GEN 49MM BLACK / NATURAL 2025",
        "$450",
        "-"
      ],
      [
        "ULTRA 3 GEN 49MM MILANESE 2025",
        "$473",
        "-"
      ],
      [
        "S11 46MM Aluminum",
        "$210",
        "-"
      ],
      [
        "S11 42mm Aluminum",
        "$195",
        "-"
      ],
      [
        "S11 46mm Titanium",
        "$315",
        "-"
      ],
      [
        "S11 42mm Titanium",
        "$293",
        "-"
      ],
      [
        "SE 3RD 44mm 3gen",
        "$150",
        "-"
      ],
      [
        "SE 3RD 40mm 3gen",
        "$135",
        "-"
      ],
      [
        "Apple Watch Ultra 2",
        "$338",
        "-"
      ],
      [
        "Apple watch Ultra 49MM",
        "$263",
        "-"
      ],
      [
        "S10 46MM Titanium",
        "$345",
        "-"
      ],
      [
        "S10 42MM Titanium",
        "$315",
        "-"
      ],
      [
        "S10 46MM Aluminum",
        "$180",
        "-"
      ],
      [
        "S10 42MM Aluminum",
        "$158",
        "-"
      ],
      [
        "S9 45MM",
        "$120",
        "-"
      ],
      [
        "S9 41MM",
        "$105",
        "-"
      ],
      [
        "SE 44mm",
        "$90",
        "-"
      ],
      [
        "SE 40mm",
        "$75",
        "-"
      ]
    ]
  },
  "ipad": {
    "headers": [
      "Model",
      "Price",
      "Note"
    ],
    "rows": [
      [
        "IPAD MINI (6th gen) 64GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD MINI (6th gen) 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD MINI (7th gen) A17 128GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD MINI (7th gen) A17 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD MINI (7th gen) A17 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M3 128GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M3 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M3 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M3 1TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M2 128GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M2 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M2 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 13\" M2 1TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M3 128GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M3 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M3 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M3 1TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M2 128GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M2 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M2 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD AIR 11\" M2 1TB",
        "Contact",
        "-"
      ],
      [
        "IPAD 11\" GEN A16 128GB",
        "Contact",
        "VZ WIFI PRICE"
      ],
      [
        "IPAD 11\" GEN A16 256GB",
        "Contact",
        "VZ WIFI PRICE"
      ],
      [
        "IPAD 11\" GEN A16 512GB",
        "Contact",
        "VZ WIFI PRICE"
      ],
      [
        "IPAD (10th gen) 64GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD (10th gen) 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 13\" M4 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 13\" M4 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 13\" M4 1TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 13\" M4 2TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 11\" (5th gen) M4 2TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 11\" (5th gen) M4 1TB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 11\" (5th gen) M4 512GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 11\" (5th gen) M4 256GB",
        "Contact",
        "-50 verizon"
      ],
      [
        "IPAD PRO 11\" (4th gen) 128GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11\" (4th gen) 256GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11\" (4th gen) 512GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11\" (4th gen) 1TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11\" (4th gen) 2TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 13in 8th Gen M5 2 TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 13in 8th Gen M5 1 TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 13in 8th Gen M5 512 GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 13in 8th Gen M5 256 GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11in 6th Gen M5 2 TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11in 6th Gen M5 1 TB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11in 6th Gen M5 512 GB",
        "Contact",
        "-"
      ],
      [
        "IPAD PRO 11in 6th Gen M5 256 GB",
        "Contact",
        "-"
      ]
    ]
  },
  "consoles": {
    "headers": [
      "Model",
      "Price",
      "Note"
    ],
    "rows": [
      [
        "Nintendo Switch 2 Mario Kart World Bundle",
        "$400",
        "Negotiable"
      ],
      [
        "Nintendo Switch 2",
        "$370",
        "Negotiable"
      ],
      [
        "Nintendo Switch OLED",
        "$240",
        "Negotiable"
      ],
      [
        "Nintendo Switch",
        "$200",
        "Negotiable"
      ],
      [
        "Nintendo Switch Lite",
        "$140",
        "Negotiable"
      ],
      [
        "Oculus Meta Quest 2 128gb",
        "$150",
        "Negotiable"
      ],
      [
        "Oculus Meta Quest 2 256gb",
        "$160",
        "Negotiable"
      ],
      [
        "Meta Quest 3s 128gb",
        "$180",
        "Negotiable"
      ],
      [
        "Meta Quest 3s 256gb",
        "$250",
        "Negotiable"
      ],
      [
        "Meta Quest 3 512gb",
        "$370",
        "Negotiable"
      ],
      [
        "Meta Quest 3 128gb",
        "$300",
        "Negotiable"
      ],
      [
        "PLAYSTATION 5 PRO",
        "$425",
        "Negotiable"
      ],
      [
        "PlayStation VR2",
        "Contact",
        "Negotiable"
      ],
      [
        "PlayStation VR2 Bundle",
        "Contact",
        "Negotiable"
      ],
      [
        "PlayStaion 5 Disc",
        "Contact",
        "Negotiable"
      ],
      [
        "PlayStation 5 Disc Bundle",
        "Contact",
        "Negotiable"
      ],
      [
        "PlayStation 5 Digital",
        "Contact",
        "Negotiable"
      ],
      [
        "Playstation 5 Digital Bundle",
        "Contact",
        "Negotiable"
      ],
      [
        "PS5 DualSense Edge Controller",
        "Contact",
        "Negotiable"
      ],
      [
        "PS5 DualSense Controller",
        "Contact",
        "Negotiable"
      ],
      [
        "PLAYSTATION PORTAL",
        "Contact",
        "Negotiable"
      ],
      [
        "Xbox Series S Digital 1TB",
        "$230",
        "Negotiable"
      ],
      [
        "Xbox Series S 512GB",
        "$200",
        "Negotiable"
      ],
      [
        "Xbox Series X 1TB",
        "$380",
        "Negotiable"
      ],
      [
        "Xbox Series X 1TB Digital",
        "$350",
        "Negotiable"
      ],
      [
        "ASUS ROG ALLY X 2TB Z1 EXTREME",
        "$425",
        "Negotiable"
      ],
      [
        "ASUS ROG ALLY X 1TB Z1 EXTREME",
        "$475",
        "Negotiable"
      ],
      [
        "ASUS ROG ALLY 512GB Z1 EXTREME",
        "$300",
        "Negotiable"
      ],
      [
        "ASUS ROG ALLY 512GB Z1",
        "$200",
        "Negotiable"
      ],
      [
        "Valve Steam Deck 256gb",
        "$200",
        "Negotiable"
      ],
      [
        "Valve Steam Deck 512gb- oled",
        "$320",
        "Negotiable"
      ],
      [
        "Valve Steam Deck 1TB- oled",
        "$400",
        "Negotiable"
      ]
    ]
  },
  "accessories": {
    "headers": [
      "Item",
      "Price",
      "Note"
    ],
    "rows": [
      [
        "Apple Pencil Gen 2",
        "Contact",
        "-"
      ],
      [
        "Apple Pencil Gen 2 Type C",
        "Contact",
        "-"
      ],
      [
        "Apple pencil pro",
        "Contact",
        "-"
      ],
      [
        "Airtag 4 pack",
        "Contact",
        "-"
      ],
      [
        "Airtag single",
        "Contact",
        "-"
      ],
      [
        "Homepod mini",
        "Contact",
        "-"
      ],
      [
        "Magic Mouse 2",
        "Contact",
        "-"
      ],
      [
        "Magic Keyboard 11\"",
        "Contact",
        "-"
      ],
      [
        "AIRPOD PRO 3 2025 ( NEW MODEL)",
        "Contact",
        "-"
      ],
      [
        "Airpod pro 2nd gen (Type C)",
        "Contact",
        "-"
      ],
      [
        "Airpod 4th Gen Noise Cancellation",
        "Contact",
        "-"
      ],
      [
        "Airpod 4th gen",
        "Contact",
        "-"
      ],
      [
        "Airpods (3rd Gen)",
        "Contact",
        "-"
      ],
      [
        "Airpods 2nd gen",
        "Contact",
        "-"
      ],
      [
        "Airpods Max",
        "Contact",
        "-"
      ],
      [
        "Airpod Max USBC",
        "Contact",
        "-"
      ]
    ]
  }
};

window.CATEGORY_LABELS = {
  "iphone": "iPhone",
  "macbook-pro": "MacBook Pro",
  "macbook-air": "MacBook Air",
  "mac-mini": "Mac Mini",
  "apple-watch": "Apple Watch",
  "ipad": "iPad",
  "consoles": "Consoles",
  "accessories": "Accessories"
};
