'use strict';
// ============================================================
// OUTPUT — assemble computed offers back into the EXACT data shape
// the quote tool already reads:
//
//   window.PRICING = { <category>: { headers:[3], rows:[[name,c1,c2]] } }
//   window.CATEGORY_LABELS = { ... }
//
// Two artifacts are produced:
//   out/pricing-data.generated.js  — drop-in replacement for the
//                                    site's /pricing-data.js
//   out/pricing.json               — the { ok, data, updated } envelope
//                                    that /api/pricing returns
//
// Frontend contract preserved:
//   - priced variant   -> "$1,234"   (parsed by form.html priceNum())
//   - manual / low data -> "Contact"  (existing hand-priced path)
//   - iPhone rows keep [unlocked, locked]; other rows keep their note col
// ============================================================

const fs = require('fs');
const path = require('path');
const { formatUSD } = require('./lib/money');

const OUT_DIR = path.join(__dirname, 'out');

/** Cell text for a computed result. */
function cell(result) {
  if (result && result.status === 'priced' && result.offer != null) return formatUSD(result.offer);
  return 'Contact';
}

/** Reuse original headers; relabel a non-price col1 header (e.g. MacBook Pro). */
function headersFor(siteCategory, originalHeaders) {
  const h = Array.isArray(originalHeaders) && originalHeaders.length === 3
    ? originalHeaders.slice()
    : ['Model', 'Price', 'Note'];
  if (/discount|msrp/i.test(String(h[1]))) h[1] = 'Est. payout';
  return h;
}

/**
 * Build window.PRICING from the catalog + a per-variant results map.
 *
 * @param catalog  output of buildCatalog()
 * @param results  Map<variantKey, headlineResult>  (from pricing.computeVariantOffers().headline-ish)
 *                 each value: { status, offer }
 * @param originalPricing  the source PRICING (for headers + row order + notes)
 * @param opts.alwaysContact  Set<siteCategory> forced to "Contact"
 */
function buildPricing(catalog, results, originalPricing, opts = {}) {
  const alwaysContact = opts.alwaysContact || new Set();
  const PRICING = {};

  for (const siteCategory of catalog.siteCategories) {
    const orig = originalPricing[siteCategory] || {};
    const headers = headersFor(siteCategory, orig.headers);
    const isPhone = siteCategory === 'iphone';
    const forceContact = alwaysContact.has(siteCategory);

    // Preserve original row order; group this category's variants by rowName.
    const variantsByRow = new Map();
    for (const v of catalog.variants) {
      if (v.siteCategory !== siteCategory) continue;
      if (!variantsByRow.has(v.rowName)) variantsByRow.set(v.rowName, []);
      variantsByRow.get(v.rowName).push(v);
    }

    const rows = [];
    for (const [rowName, vs] of variantsByRow) {
      let c1 = 'Contact';
      let c2 = isPhone ? 'Contact' : '—';
      for (const v of vs) {
        const r = forceContact ? { status: 'needs_manual_price' } : results.get(v.variantKey);
        const text = cell(r);
        if (v.outputColumn === 1) c1 = text;
        if (isPhone && v.outputColumn === 2) c2 = text;
        if (!isPhone) c2 = v.sourceNote != null && v.sourceNote !== '' ? v.sourceNote : '—';
      }
      rows.push([rowName, c1, c2]);
    }

    PRICING[siteCategory] = { headers, rows };
  }

  return PRICING;
}

/** Serialize to a drop-in pricing-data.js file body. */
function toPricingDataJs(PRICING, CATEGORY_LABELS, meta = {}) {
  const banner =
    `// AUTO-GENERATED by pricing-engine on ${meta.updated || new Date().toISOString()}.\n` +
    `// Source(s): ${(meta.sources || ['ebay']).join(', ')}. DO NOT EDIT BY HAND —\n` +
    `// edit pricing-engine/config.js and re-run \`node build-prices.js\`.\n` +
    `// Drop-in replacement for /pricing-data.js (same window.PRICING shape).\n`;
  return (
    banner +
    `window.PRICING = ${JSON.stringify(PRICING, null, 2)};\n\n` +
    `window.CATEGORY_LABELS = ${JSON.stringify(CATEGORY_LABELS, null, 2)};\n`
  );
}

/** The /api/pricing envelope. */
function toApiEnvelope(PRICING, updated) {
  return { ok: true, data: PRICING, updated: updated || new Date().toISOString() };
}

// ------------------------------------------------------------
// OFFERS MODULE — condition-aware first offers for /api/inquiry.
// Written as an ES module under api/_pricing/ (underscore = not exposed
// as an endpoint) so the edge function bundles it privately; the full
// per-condition offer ladder is NOT publicly downloadable.
// ------------------------------------------------------------

/** Lookup key: lowercase, collapsed whitespace (sheet casing drifts). */
function normName(s) {
  return String(s || '').toLowerCase().replace(/\s+/g, ' ').trim();
}

/**
 * Build the offers lookup for the inquiry endpoint.
 *
 * @param catalog        output of buildCatalog()
 * @param byConditionMap Map<variantKey, byCondition>  (full computeVariantOffers
 *                       results: { 'like new': result, good: result, ... })
 * @param config         engine config (for CONDITION_ALIASES)
 */
function buildOffers(catalog, byConditionMap, config, meta = {}) {
  const alwaysContact = new Set((config.output && config.output.alwaysContact) || []);
  const categories = {};
  for (const v of catalog.variants) {
    if (alwaysContact.has(v.siteCategory)) continue; // hand-priced stays hand-priced
    const byCond = byConditionMap.get(v.variantKey);
    if (!byCond) continue;
    const tiers = {};
    let any = false;
    for (const [tier, r] of Object.entries(byCond)) {
      tiers[tier] = r && r.status === 'priced' ? r.offer : null;
      if (tiers[tier] != null) any = true;
    }
    if (!any) continue; // all-manual variants stay off the auto-offer path
    const slot = v.carrier === 'locked' ? 'locked' : v.carrier === 'unlocked' ? 'unlocked' : 'default';
    const cat = (categories[v.siteCategory] = categories[v.siteCategory] || {});
    const entry = (cat[normName(v.rowName)] = cat[normName(v.rowName)] || {});
    entry[slot] = tiers;
  }

  const labelToKey = {};
  for (const [key, label] of Object.entries(catalog.categoryLabels || {})) {
    labelToKey[normName(label)] = key;
  }

  const conditionAliases = {};
  for (const [label, tier] of Object.entries(config.CONDITION_ALIASES || {})) {
    conditionAliases[normName(label)] = tier;
  }

  return {
    updated: meta.updated || new Date().toISOString(),
    sources: meta.sources || [],
    labelToKey,
    conditionAliases,
    defaultCondition: 'good',
    display: {
      minVsEstimateRatio:
        (config.output && config.output.customerDisplayMinRatio) != null
          ? config.output.customerDisplayMinRatio
          : 0.75,
    },
    categories,
  };
}

function toOffersModuleJs(offers) {
  return (
    `// AUTO-GENERATED by pricing-engine on ${offers.updated}. DO NOT EDIT —\n` +
    `// re-run \`node build-prices.js\`. Condition-aware first offers consumed\n` +
    `// by api/inquiry.js. Underscore path keeps it out of public routes.\n` +
    `export default ${JSON.stringify(offers, null, 2)};\n`
  );
}

function writeOffers(offers) {
  const apiPath = path.join(__dirname, '..', 'api', '_pricing', 'offers.generated.js');
  const outPath = path.join(OUT_DIR, 'offers.json');
  fs.mkdirSync(path.dirname(apiPath), { recursive: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(apiPath, toOffersModuleJs(offers));
  fs.writeFileSync(outPath, JSON.stringify(offers, null, 2));
  return { apiPath, outPath };
}

function writeOutputs(PRICING, CATEGORY_LABELS, meta = {}) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const updated = meta.updated || new Date().toISOString();
  const jsPath = path.join(OUT_DIR, 'pricing-data.generated.js');
  const jsonPath = path.join(OUT_DIR, 'pricing.json');
  fs.writeFileSync(jsPath, toPricingDataJs(PRICING, CATEGORY_LABELS, { ...meta, updated }));
  fs.writeFileSync(jsonPath, JSON.stringify(toApiEnvelope(PRICING, updated), null, 2));
  return { jsPath, jsonPath };
}

module.exports = {
  buildPricing, toPricingDataJs, toApiEnvelope, writeOutputs, cell, headersFor, OUT_DIR,
  buildOffers, toOffersModuleJs, writeOffers, normName,
};
